
inputexpression:
	gcc -O2 -g  inputexpression.c ../src/execpipeline.c ../src/pipelinemath.c  ../src/expressionparser.c -o inputexpression && ./inputexpression && rm ./inputexpression

test_input:
	echo NotImplemented
